# fly.toml app configuration file generated for bot-rui on 2023-12-30T00:04:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bot-rui"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 8192
